version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py
  builder: dirhtml
  fail_on_warning: true

formats: all

python:
  install:
  - requirements: docs/requirements.txt
