name: Release on GitHub and PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  run_tests:
    name: Run tests before publishing
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sblauth/cashocs:main
      options: --user=root

    steps:
    - name: Delete current installation in docker image
      shell: bash
      run: |
        source /usr/local/bin/_entrypoint.sh
        pip uninstall -y cashocs
        rm -R /home/mambauser/cashocs

    - name: Checkout repository
      uses: actions/checkout@v4.1.1 

    - name: Install cashocs
      shell: bash
      run: |
        source /usr/local/bin/_entrypoint.sh
        pip install .[all]

    - name: Run tests
      shell: bash
      run: |
        source /usr/local/bin/_entrypoint.sh
        python3 -m pytest -vv tests/


  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      - run_tests
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
    

    - name: Get tag name
      id: tag_name
      run: |
        echo "::set-output name=TAG_PREFIX::${GITHUB_REF#refs/tags/}"


    - name: Check if release is a pre-release
      id: check_version
      uses: nowsprinting/check-version-format-action@v3
      with:
        prefix: 'v'


    - name: Create Github release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: cashocs ${{ steps.tag_name.outputs.TAG_PREFIX }}
        generate_release_notes: ${{ steps.check_version.outputs.is_stable == 'true' }}
        prerelease: ${{ steps.check_version.outputs.is_stable == 'false' }}


  build_and_publish:
    name: Build and publish python package
    runs-on: ubuntu-latest
    needs:
      - run_tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install pypa/build
      run: python -m pip install build --user

    - name: Build a binary wheel and a source tarball
      run: python -m build --sdist --wheel --outdir dist/ .

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
